apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job