apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefun-deployment
  labels:
    app: kubefun
spec:
  selector:
    matchLabels:
      app: kubefun
  template:
    metadata:
      labels:
        app: kubefun
    spec:
      containers:
      - name: kubefun
        image: localhost:32000/kubefun:registry
        ports:
        - containerPort: 9000
