apiVersion: v1
kind: Pod
metadata:
  name: kubefun-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: whatsadebugger/kubefun
    name: kubefun
    ports:
    - containerPort: 9000
      protocol: TCP