apiVersion: v1
kind: ReplicationController
metadata:
  name: kubefun
spec:
  replicas: 3
  selector:
    app: kubefun
  template:
    metadata:
      name: kubefun
      labels:
        app: kubefun
    spec:
      containers:
      - name: kubefun
        image: whatsadebugger/kubefun
        ports:
        - containerPort: 9000
